---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.6
  - name: centos-6.4
    driver:
      box: opscode-centos-6.4
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef_server_populator:
        endpoint: localhost
        solo_org:
          validator_pub_key: validator_pub.pem
        org_users:
          pub_key: user_pub.pem
        clients:
          test-node: client_key_pub.pem
  - name: default-specific-chef
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef-server:
        version: 12.5.0
      chef_server_populator:
        endpoint: localhost
        solo_org:
          validator_pub_key: validator_pub.pem
        org_users:
          pub_key: user_pub.pem
        clients:
          test-node: client_key_pub.pem
  - name: default-old-chef
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef-server:
        version: 12.0.7-1
      chef_server_populator:
        endpoint: localhost
        solo_org:
          validator_pub_key: validator_pub.pem
        org_users:
          pub_key: user_pub.pem
        clients:
          test-node: client_key_pub.pem
  - name: data-bag
    provisioner:
      name: chef_zero
    data_bags_path: test/fixtures/data_bags
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef_server_populator:
        endpoint: localhost
        databag: chef
  - name: data-bag-old-chef
    provisioner:
      name: chef_zero
    data_bags_path: test/fixtures/data_bags
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef-server:
        version: 12.0.7-1
      chef_server_populator:
        endpoint: localhost
        databag: chef
  - name: backups
    run_list:
      - recipe[test]
      - recipe[build-essential]
      - recipe[chef-server-populator]
      - recipe[chef-server-populator::backups]
    attributes:
      chef_server_populator:
        endpoint: localhost
        solo_org:
          validator_pub_key: validator_pub.pem
        org_users:
          pub_key: user_pub.pem
        clients:
          test-node: client_key_pub.pem
        backup:
          remote:
            connection: false
            directory: false
